version: "3.8"

services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: etmg-postgres
    environment:
      POSTGRES_DB: explain_to_me_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etmg-network

  # User API
  user-api:
    build: ./user-api
    container_name: etmg-user-api
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/explain_to_me_db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
      JWT_SECRET: explain-to-me-genius-secret-2025
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    depends_on:
      - postgres
    networks:
      - etmg-network

networks:
  etmg-network:
    driver: bridge

volumes:
  postgres_data:
