spring:
  application:
    name: user-api

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/explain_to_me_db}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

jwt:
  secret: ${JWT_SECRET:explain-to-me-genius-secret-2025}
  expiration: 86400000
